### ISSUE TITLE
Backdrop highlight target

### ISSUE THREAD

**Issue by dotsoftwarenl** [GlobalHive/vuejs-tour#65]
Hi,

The screenshot below only shows the vjt-tour element highlighted, but I would like to also highlight the section whilst using backdrop. Is there a way to also highlight the target instead of the blue line around it?

![Screenshot 2024-07-17 at 11 00 51](https://github.com/user-attachments/assets/7e0db69f-93ee-4e77-a790-b8554f699c07)

Love the package so far!

**Comment by GlobalHive** [comment]
Hi @dotsoftwarenl,
it should do that already when using the highlight.

How did you setup the Tour?
Or: Looks like you changed the styling a bit, make sure to keep the z-index of `vjt-hightlight` above the backdrop.

![Screenshot 2024-07-17 195425](https://github.com/user-attachments/assets/8b139329-468c-49c3-b587-e241d6c96d0a)

**Comment by chboing** [comment]
Hello, i've been testing your lib but I'm using Quasar framework for vuejs,, and i'm facing a problem.
When you're using some component like q-splitter, they redefine a stacking context (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context) by setting `position: relative` in the comp CSS
So it's not possible to slip a z-index above the backdrop because it's not in the same stacking context.
I think there is no solution to this as it is.

This would be solved for any cases, if the backdrop was not a single div, but 4 divs instead like so:
![image](https://github.com/user-attachments/assets/3adf3d9c-5ff3-4e0d-9a99-0456905e892a)

what do you think ? maybe another prop on VTour to enable the splitted backdrop ? This would mean i can use your lib

**Comment by GlobalHive** [comment]
Hello @chboing 

Thank you for your response. If Quasar redefines the stacking context, then yes, VueJS-Tour will not function as expected.

I will add a "Quasar switch" prop to the component, utilizing your 4-div approach. Could you please open a new issue for this so I can close the current one, as it appears to be resolved or inactive?

Sincerely,
Sascha

**Comment by chboing** [comment]
Just created a ticket here : https://github.com/GlobalHive/vuejs-tour/issues/67
👍
